version: '3.8'
services:
  flutter-frontend:
    build:
      context: ./online_bilet_satis # Flutter uygulamanın bulunduğu dizin
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Flutter uygulamasına erişmek için
    depends_on:
      - go-backend

  go-backend:
    build:
      context: ./mobil-backend # Go uygulamanın bulunduğu dizin
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Go servisine erişmek için




